config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        sessions: 'api/v1/sessions'
      }

      resources :dashboard do
        member do
          post :update_result
          get :get_so
        end
        collection do
          post :return_data
          post :update_status
          post :get_user_info
          post :remove
          post :report
        end
      end


      resources :informations do
        collection do
          get :vendors
          get :customers
          post :remove
        end
      end


      resources :debit_notes do
        collection do
          post :remove
          get :get_pdf
          post :submit
          post :return_data
        end
      end

      resources :payment_requests do
        collection do
          post :remove
          get :get_pdf
          post :submit
          post :return_data
        end
      end

    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root 'home#index'
  # root 'service_order#index'

  get '/tvpl' => 'home#index'
  get 'page-about-us' => 'home#about_us'
  get 'page-pricing' => 'home#pricing'
  get 'page-faq' => 'home#faq'
  get 'page-contact' => 'home#contact'
  get 'page-news' => 'home#news'
  get 'page-logistics-service' => 'home#logistics_service'
  get 'page-leadership' => 'home#leadership'
  get 'page-careers' => 'home#careers'

  get 'contact' => 'home#contact'
  get 'logistics_service' => 'home#logistics_service'
  get 'pricing' => 'home#pricing'
  get 'faq' => 'home#faq'
  get 'about_us' => 'home#about_us'
  get 'careers' => 'home#careers'

  scope 'dashboard' do
    get '' => 'service_order#dashboard', as: 'dashboard'
    get 'new' => 'service_order#new'
    post 'create' => 'service_order#create', as: 'dashboard_create'
    get 'edit/:id' => 'service_order#edit', as: 'dashboard_edit'
    post 'update/:id' => 'service_order#update', as: 'dashboard_update'

    get 'delete/:id' => 'service_order#delete', as: 'dashboard_delete'
    get 'rollback/:id' => 'service_order#rollback', as: 'dashboard_rollback'
    get 'change_status/:id' => 'service_order#change_status', as: 'dashboard_change_status'
    get 'data' => 'service_order#data', as: 'dashboard_data'
  end

  resource :business_plans do
    get 'data' => 'business_plans#data'
    post 'update_attr' => 'business_plans#update_attr'
    get 'update_done_so/:id' => 'business_plans#update_done_so'
  end

  resources :file_data do
    post 'add_data' => 'file_data#add_data'
    get 'truck/:id' => 'file_data#truck', on: :collection
    get 'barge/:id' => 'file_data#barge', on: :collection
    get 'load/:id' => 'file_data#load', on: :collection
    get 'discharge/:id' => 'file_data#discharge', on: :collection
    get 'internal/:id' => 'file_data#internal', on: :collection
    get 'external/:id' => 'file_data#external', on: :collection
    get 'so_disc/:id' => 'file_data#so_disc', on: :collection
    get 'so_load/:id' => 'file_data#so_load', on: :collection
    get 'so_cont/:id' => 'file_data#so_cont', on: :collection
    get 'so_bk/:id' => 'file_data#so_bk', on: :collection
    post 'update_result', on: :collection
    post 'upload_file', on: :collection
  end

  resources :payment_requests do
    post 'add_data'
    get 'edit/:id' => 'payment_requests#edit'
    get 'data', on: :collection
    get 'list', on: :collection
    post 'update_attr', on: :collection
    post 'create_pr_without_so', on: :collection
    post 'update_done_status', on: :collection
    post 'remove_row', on: :collection
  end

  resources :debit_notes do
    get 'edit/:id' => 'debit_notes#edit'
    get 'data', on: :collection
    get 'list', on: :collection
    post 'update_attr', on: :collection
    post 'create_pr_without_so', on: :collection
    post 'update_done_status', on: :collection
    post 'remove_row', on: :collection
  end

  resources :informations, only: [:index] do
    get 'vendors', on: :collection
    post 'add_data', on: :collection
    post 'update_attr', on: :collection
    get 'customers', on: :collection
    post 'vendors', on: :collection
    post 'customers', on: :collection
  end

  get 'activity' => 'service_order#activity'
  get 'analytics' => 'service_order#analytics'
  get 'profit' => 'service_order#profit'
  get 'pivot' => 'service_order#pivot'
  get 'analytics/data' => 'service_order#data_analytics'
  get 'quote' => 'service_order#quote'


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
end

app/models/service_order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: service_orders
#
#  id               :bigint           not null, primary key
#  bill_of_lading   :string
#  branch           :string           default("tvpl")
#  commodity        :string
#  contract         :string
#  customer         :string
#  customer_no      :string
#  date_so          :date
#  deleted_at       :datetime
#  description      :string
#  docs_date        :date
#  end              :date
#  equipment        :string
#  key_customer     :string
#  location         :string
#  month            :integer
#  name_of_vessel   :string
#  payment_due_date :date
#  so               :string
#  so_type          :string
#  start            :date
#  status           :integer          default("listing"), not null
#  type_cargo       :string
#  vehicle          :string
#  vendor           :string
#  vendor_key       :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_service_orders_on_deleted_at  (deleted_at)
#
class ServiceOrder < ApplicationRecord
  acts_as_paranoid
  serialize :vendor, coder: JSON
  serialize :customer, coder: JSON

  enum status: { done: 1, listing: 0 }

  has_many :user_service_orders, dependent: :destroy
  has_many :users, through: :user_service_orders

  has_one :result, dependent: :destroy
  # has_one :business_plan, dependent: :destroy
  has_one :file_data, dependent: :destroy

  has_many :payment_requests, dependent: :destroy
  has_many :debit_notes, dependent: :destroy

  accepts_nested_attributes_for :users

  after_create :create_business_plan
  after_update :after_update_data

  validates :so, presence: true

  def create_business_plan
    Result.create({ service_order_id: id })
  end

  def after_update_data
    return unless saved_change_to_so?

    DebitNote.where(service_order_id: id).update_all(so:)
    PaymentRequest.where(service_order_id: id).update_all(so:)

  end

end

app/controllers/service_order_controller.rb
# frozen_string_literal: true
class ServiceOrderController < ApplicationController
  before_action :authenticate_user!, except: [:quote]
  before_action :authenticate_admin!, only: %i[create delete change_status analytics profit data_analytics rollback]

  def index
    redirect_to dashboard_path
  end

  def analytics
    @report_tvpl = ServiceOrder.where(branch: 'tvpl').joins(:result).group(:month).select('service_orders.month, SUM(results.grand_total) as total_grand').order(month: :asc)
    @report_nnp = ServiceOrder.where(branch: 'nnp').joins(:result).group(:month).select('service_orders.month, SUM(results.grand_total) as total_grand').order(month: :asc)
    @grand = ServiceOrder.joins(:result).select(
      'SUM(results.tvpl_load) as total_load',
      'SUM(results.discharge) as total_discharge',
      'SUM(results.tvpl_truck) as total_truck',
      'SUM(results.tvpl_barge) as total_barge',
      'SUM(results.internal_wh + results.external_wh) as total_wh',
      'SUM(results.grand_total) as total_grand'
    )
    @grand_tvpl = ServiceOrder.where(branch: 'tvpl').joins(:result).select(
      'SUM(results.tvpl_load) as total_load',
      'SUM(results.discharge) as total_discharge',
      'SUM(results.tvpl_truck) as total_truck',
      'SUM(results.tvpl_barge) as total_barge',
      'SUM(results.internal_wh + results.external_wh) as total_wh',
      'SUM(results.grand_total) as total_grand'
    )
    @grand_nnp = ServiceOrder.where(branch: 'nnp').joins(:result).select(
      'SUM(results.tvpl_load) as total_load',
      'SUM(results.discharge) as total_discharge',
      'SUM(results.tvpl_truck) as total_truck',
      'SUM(results.tvpl_barge) as total_barge',
      'SUM(results.internal_wh + results.external_wh) as total_wh',
      'SUM(results.grand_total) as total_grand'
    )
  end

  def pivot

  end

  def profit

  end

  def activity
    redirect_to dashboard_path unless current_user.id == 1 || current_user.id == 7
    so_ids = Result.where(updated_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).pluck(:service_order_id)
    @files = ServiceOrder.includes(:result, :users).where(id: so_ids).to_json(include: { result: {}, users: { only: [:name] } })
  end

  def data_analytics
    months = params[:months] || 1
    commodity = ServiceOrder.where(branch: @branch).pluck(:type_cargo).uniq
    arr = []
    if params['type'].present?
      # data = ServiceOrder.where(branch: @branch).includes(:debit_notes, :payment_requests)
      # arr = data
      dn_list = DebitNote.where("EXTRACT(MONTH FROM date) in (?) AND branch = ? AND status = ?", months, @branch, '2').pluck(:so)
      pq_list = PaymentRequest.where('EXTRACT(MONTH FROM payment_date) in (?) AND branch = ? AND status = ?', months, @branch, '2').pluck(:so)
      so_list = (dn_list + pq_list).uniq
      dn_ids = DebitNote.where("EXTRACT(MONTH FROM date) IN (?)  AND branch = ? AND status = ?", months, @branch, '2').ids
      pq_ids = PaymentRequest.where("EXTRACT(MONTH FROM payment_date) in (?)  AND branch = ? AND status = ?", months,@branch, '2').ids
      so_list.each do |s|
        arr.push({ so: s, payment_requests: PaymentRequest.where(id: pq_ids, so: s, status: 2), debit_notes: DebitNote.where(id: dn_ids, so: s, allow: 2) })
      end
      arr = arr.sort_by { |e| e[:so] == '' ? 1 : 0 }
    else

      commodity.each_with_index do |c, i|
        data = ServiceOrder.where(month: months, branch: @branch).joins(:result).group(:key_customer, :type_cargo).select('service_orders.key_customer , SUM(results.tvpl_load) as total_load,
       SUM(results.discharge) as total_discharge, SUM(results.tvpl_truck) as total_truck,
      SUM(results.tvpl_barge) as total_barge,(SUM(results.internal_wh) + SUM(results.external_wh)) as total_wh, SUM(results.grand_total) as total_grand').where(type_cargo: c)
        arr.push({ type_cargo: c, data: })
      end
    end
    if params['type'].present?
      respond_to do |format|
        format.json { render json: { "data": arr.as_json } }
      end
    else
      respond_to do |format|
        format.json { render json: { "data": arr } }
      end

    end

  end

  def delete
    if current_user.id == 1 || current_user.id == 7
      so = ServiceOrder.find_by(id: params[:id])
      so.destroy
      text = { user: current_user.name,
               params:}
      TeleService.send_message(text)
      flash[:notice] = 'Remove SO Successful'
    else
      flash[:notice] = "Don't have permission for this action "
    end
    render js: "window.location = '/dashboard'"
  end

  def rollback
    if current_user.id == 1 || current_user.id == 7
      so = ServiceOrder.find_by(id: params[:id])
      so.update_column(:status, :listing)
      flash[:notice] = 'Update Successful'
    else
      flash[:notice] = "Don't have permission for this action "
    end
    render js: "window.location = '/dashboard'"

  end

  def change_status
    if current_user.id == 1 || current_user.id == 7
      so = ServiceOrder.find_by(id: params[:id])
      so.update_column(:status, :done)
      text = { user: current_user.name,
               params:}
      TeleService.send_message(text)
      flash[:notice] = 'Successful'
    else
      flash[:notice] = "Don't have permission for this action"
    end
    render js: "window.location = '/dashboard'"
  end

  def dashboard
    # ServiceOrder
  end

  def new
    @service_order = ServiceOrder.new
    @service_order.user_service_orders.build
  end

  def edit
    @service_order = ServiceOrder.find(params[:id])
    @service_order.user_service_orders.build
  end

  def update
    @service_order = ServiceOrder.find(params[:service_order][:id])

    if @service_order.update(service_order_params)
      current_user.admin? ? redirect_to(dashboard_path) : redirect_to(business_plans_path)
      flash[:notice] = 'Update Successful'
    else
      flash[:notice] = @service_order.errors.full_messages.join('<br/>')
    end
  end

  def create
    if params[:service_order][:user_service_orders_attributes].present?
      params[:service_order][:user_service_orders_attributes].each_value do |value|
        params[:service_order][:user_service_orders_attributes]['user_id'] = value.map(&:to_i)
      end
    end
    @service_order = ServiceOrder.new(service_order_params)
    if @service_order.save
      redirect_to dashboard_path, notice: 'Service order was successfully created.'
    else
      redirect_to dashboard_new_path
      flash[:notice] = @service_order.errors.full_messages.join('<br/>')
    end
  end

  def data
    query = ServiceOrder.where(branch: @branch).includes(:users).left_joins(:file_data, :result)
                        .select('* , service_orders.id as id, service_orders.description as description').order(:month, :so, created_at: :asc)
    if params[:type] == 'done'
      query = query.where(status: :done)
    else
      query = query.where(status: :listing)
    end
    data = { "data": query }
    respond_to do |format|
      format.json { render json: data.as_json(include: { users: { only: [:name] } }) }
    end
  end

  def quote
    @no_navbar = true
  end

  private

  def service_order_params
    params.require(:service_order).permit(:id, :month, :date_so, :equipment, :so, :commodity, :description, :service,
                                          :location, :type_cargo, :vehicle, :name_of_vessel,
                                          :customer_no, :key_customer, :vendor_key, :so_type,
                                          :branch, user_ids: [], vendor: [], customer: [])
  end
end

app/views/service_order/activity.html.erb
<input type="hidden" id="activity" value="<%= @files %>"/>

<div class="mt-3">
  <!--  <div class="flex pb-3 justify-end round">-->
  <!--    <input class="rounded" type="text" id="filter-text-box" placeholder="Key word...">-->
  <!--  </div>-->
  <div id="myGrid" class="ag-theme-quartz" style="height: 600px; ">
  </div>
  <!--  <div class="flex justify-end">-->
  <!--    <button id="addButton" class="bg-sky-400 px-4 py-2 rounded  mr-4 mt-2  text-white font-bold"> Add-->
  <!--    </button>-->
  <!--  </div>-->
</div>


<script type="module">
    $(document).ready(function () {
        var activity = JSON.parse($('#activity').val())
        const gridOptions = {
            autoSizeStrategy: {
                type: 'fitGridWidth'
            },
            columnDefs: [
                {
                    field: 'so',
                    headerName: 'SO',
                    cellDataType: 'text',
                },
                {
                    field: 'users.name',
                    headerName: 'USER',
                    cellDataType: 'text',
                    cellRenderer: function (params) {
                        let name = params.data.users.map(e => e.name)
                        return name.join(', ')
                    }
                },
                {
                    field: 'result.updated_at',
                    headerName: 'TIME',
                    cellDataType: 'text',
                    cellRenderer: function (params) {
                        var date = moment(params.data.result.updated_at)
                        return date.format("MM/DD/YYYY HH:mm:ss")
                    }
                },
                {
                    field: 'result.tvpl_truck',
                    headerName: 'TRUCK',
                    type: 'numberColumn',
                },
                {
                    field: 'result.tvpl_barge',
                    headerName: 'BARGE',
                    type: 'numberColumn',
                },
                {
                    field: 'result.tvpl_load',
                    headerName: 'LOAD',
                    type: 'numberColumn',
                },
                {
                    field: 'result.discharge',
                    headerName: 'DISCHARGE',
                    type: 'numberColumn',
                },
                {
                    field: 'result.internal_wh',
                    headerName: 'INTERNAL ',
                    type: 'numberColumn',
                },
                {
                    field: 'result.external_wh',
                    headerName: 'EXTERNAL',
                    type: 'numberColumn',
                }

            ],
            columnTypes: {
                numberColumn: {
                    valueFormatter: function (params) {
                        if (!params.value) {
                            return ''
                        }
                        return parseFloat(params.value).toLocaleString()
                    },
                },
            }

        }

        const myGridElement = document.querySelector('#myGrid');

        var gridApi = agGrid.createGrid(myGridElement, gridOptions)

        gridApi.setGridOption('rowData', activity)
        console.table(activity)
        console.log(activity)

    })
</script>

app/views/service_order/edit.html.erb
<div class="flex min-h-full flex-col justify-center px-6 lg:px-8 ">
  <div class="mt-5 sm:mx-auto sm:w-full  shadow p-4">
    <%= form_with(model: @service_order, url: dashboard_update_path, method: :post) do |f| %>
      <%= f.hidden_field :id %>
      <div class="flex flex-wrap">
        <div class="mt-2 w-1/4 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Branch</label>
          <%= f.select :branch, ['tvpl', 'nnp'], { include_hidden: false }, { multiple: false, disabled: true, class: "bg-gray-300 pointer-events-none w-full block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :month, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :month, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :date_so, 'Date SO', class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.date_field :date_so, placeholder: 'mm/dd/yyyy', class: " date-picker block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Type</label>
          <%= f.select :so_type, ['SO', 'SO DISC', 'SO LOAD', 'SO CONT','SO BINH KHUONG'], { include_hidden: false }, { multiple: false, disabled: true, class: "w-full block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
        </div>

        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :so, 'S/O No.', class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :so, class: "bg-gray-300 pointer-events-none block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>

        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :location, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :location, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :equipment, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :equipment, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :type_cargo, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :type_cargo, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">CS</label>
          <%= f.collection_select :user_ids, User.all, :id, :name, {}, { multiple: true, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' } %>
        </div>


        <div class="field mt-2 w-1/4 px-4">
          <%= f.label 'Key Customer', class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :key_customer, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <%= f.label :customer, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :customer_no, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/4 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Customer full</label>
          <%= f.select :customer, Customer.pluck(:name), { include_hidden: false }, { multiple: true, class: "w-full block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
        </div>
        <div class="field mt-2 w-1/2 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Vendor</label>
          <%= f.text_field :vendor_key, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/2 px-4">
          <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Vendor Full</label>
          <%= f.select :vendor, Vendor.pluck(:name), { include_hidden: true }, { multiple: true, class: "w-full block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" } %>
        </div>

        <div class="field mt-2 w-1/2 px-4">
          <%= f.label :commodity, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :commodity, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/2 px-4">
          <%= f.label :vehicle, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :vehicle, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
        <div class="field mt-2 w-1/2 px-4">
          <%= f.label :name_of_vessel, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :name_of_vessel, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>

        <div class="field mt-2 w-1/2 px-4">
          <%= f.label :description, 'Work content', class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= f.text_field :description, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div>
        <div class="actions">
          <%= f.submit "Update", class: "cursor-pointer mt-5 flex mx-auto w-25 justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<style>
    .select2-container .select2-selection--single {
        min-height: 32px;
    }
</style>

<script type="module">
    $(document).ready(function () {
        $('select').not('.not-select-2').select2()
    })
</script>

app/views/service_order/index.html.erb
sam

app/views/service_order/pivot.html.erb
<div id="app">
  <button @click="increment">Count is: {{ count }}</button>
</div>
<script type="module">

    vue.createApp({
        data() {
            return {
                count: 0
            }
        }
    }).mount('#app')

</script>

app/views/service_order/quote.html.erb
<div id="app"></div>

app/views/service_order/upload.html.erb
<div class="container shadow">
  <div>
    <span>SO</span>
    <%= form_with url: "/dashboard/upload", multipart: true, method: 'post' do |form| %>
      <%= file_field_tag :file %>
      <%= submit_tag %>
    <% end %>
  </div>

  <div class="mt-4">
    <span>Customer and Vendor</span>

    <%= form_with url: "/dashboard/upload_legend", multipart: true, method: 'post' do |form| %>
      <%= file_field_tag :file %>
      <%= submit_tag %>
    <% end %>
  </div>

  <div class="mt-4">
      <%= @so.to_json %>
  </div>



</div>